// src/client/modules/ai-summary.ts
// Manages the AI image summary popup.

import { ICONS_SVG } from './icons-svg.ts';

let modal: HTMLElement | null = null;

function ensureModal(): HTMLElement {
    if (modal) return modal;

    modal = document.createElement('div');
    modal.id = 'ai-summary-modal';
    modal.className = 'hidden fixed inset-0 z-50 flex items-end justify-center sm:items-center p-4 bg-black/50 backdrop-blur-sm';
    modal.innerHTML = `
        <div class="bg-white dark:bg-vsdark-surface rounded-2xl shadow-2xl w-full max-w-sm p-5 relative animate-fade-in-up">
            <button id="ai-summary-close"
                class="absolute top-3 right-3 w-7 h-7 flex items-center justify-center rounded-full text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-vsdark-border transition-colors"
                aria-label="Close">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
            </button>
            <div class="flex items-center gap-2 mb-3">
                <span class="w-5 h-5 text-purple-500 dark:text-purple-400 shrink-0">${ICONS_SVG.sparkle}</span>
                <h3 class="text-sm font-semibold text-slate-700 dark:text-vsdark-text">AI Image Summary</h3>
            </div>
            <p id="ai-summary-text"
               class="text-sm text-slate-600 dark:text-vsdark-text-muted leading-relaxed whitespace-pre-wrap"></p>
            <p class="text-[10px] text-slate-400 dark:text-vsdark-text-muted mt-3">
                Generated by local Ollama — may not be accurate.
            </p>
        </div>
    `;

    document.body.appendChild(modal);

    modal.addEventListener('click', (e: MouseEvent) => {
        if (e.target === modal) closeAiSummaryModal();
    });
    modal.querySelector('#ai-summary-close')!.addEventListener('click', closeAiSummaryModal);

    return modal;
}

export function showAiSummary(text: string): void {
    const m = ensureModal();
    m.querySelector<HTMLElement>('#ai-summary-text')!.textContent = text;
    m.classList.remove('hidden');
}

function closeAiSummaryModal(): void {
    modal?.classList.add('hidden');
}

/**
 * Called when the server broadcasts `aiSummaryReady` for a post.
 * Updates the AI button on the matching post card so users can click it.
 */
export function handleAiSummaryUpdate(postId: number, aiSummary: string): void {
    const btn = document.querySelector<HTMLButtonElement>(`[data-ai-btn="${postId}"]`);
    if (!btn) return;

    btn.dataset.aiSummary = aiSummary;
    btn.disabled = false;
    btn.title = 'View AI image summary';
    btn.classList.remove('text-slate-300', 'dark:text-slate-600', 'cursor-wait', 'animate-pulse');
    btn.classList.add('text-purple-500', 'dark:text-purple-400', 'cursor-pointer', 'hover:text-purple-700');

    const label = btn.querySelector<HTMLElement>('.ai-btn-label');
    if (label) label.textContent = 'AI Summary';
}
